[project]
name = "interval-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "types-requests>=2.32.4.20250913",
    "openai>=1.0.0",
]
